### ISSUE TITLE
Dimension of Matrices

### ISSUE THREAD

**Issue by letian-w** [sstoikov/microprice#3]
In cell 7 of the [notebook](https://github.com/sstoikov/microprice/blob/master/Microprice%20-%20Big%20Data%20Conference.ipynb), the `estimate` function is defined as the following.

``` python
def estimate(T):

    # LINES OMMITED

    Q_counts=np.resize(np.array(no_move_counts[0:(n_imb*n_imb)]),(n_imb,n_imb))
    # loop over all spreads and add block matrices
    for i in range(1,n_spread):
        Qi=np.resize(np.array(no_move_counts[(i*n_imb*n_imb):(i+1)*(n_imb*n_imb)]),(n_imb,n_imb))
        Q_counts=block_diag(Q_counts,Qi)

    # LINES OMMITED
    
    return G1,B,Q,Q2,R1,R2,K
```

Should this be `n_imb*n_spread` instead of `n_imb*n_imb`? In the [paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2970694), matrix **Q** is of dimension *nm* by *nm*, where *n* and *m* are discretized grids of *I* and *S* respectively.

**Comment by sstoikov** [comment]
In the end of the loop the Q matrix is of size n_imb*n_spread by
n_imb*n_spread

It is made up of n_spread blocks of n_imb by n_imb matrices

**Comment by letian-w** [comment]
Got it, thank you @sstoikov. That was my oversight.
